<pre class='metadata'>
Title: ActivityPub Server-to-Service Content Delivery
Shortname: activitypub-service-content-delivery
Level: None
Status: w3c/UD
Repository: explainers-by-googlers/activitypub-service-content-delivery
URL: https://explainers-by-googlers.github.io/activitypub-service-content-delivery
Editor: Liam Roche, Google https://google.com, liamroche@google.com
Abstract: A standardized mechanism for ActivityPub servers to deliver public content to third-party ActivityPub services.
Markup Shorthands: markdown yes, css no
Complain About: accidental-2119 yes, missing-example-ids yes
Assume Explicit For: yes
Die On: warning
</pre>

Introduction {#intro}
=====================

For now, see the <a href=[REPOSITORYURL]>explainer</a>.

See [https://garykac.github.io/procspec/](https://garykac.github.io/procspec/),
[https://dlaliberte.github.io/bikeshed-intro/index.html](https://dlaliberte.github.io/bikeshed-intro/index.html),
and [https://speced.github.io/bikeshed/](https://speced.github.io/bikeshed/) to get started on your
specification.
